### PR TITLE
Better map marker distribution

### LINKED ISSUE #11: Multiple users in the same city don't show up
It seems like all users in the same city have the marker at exactly the same positions, which makes it so that you only see the marker of the last user.
Maybe we should add a little bit of random to the markers which have a very general location (like Berlin)?

### PR DESCRIPTION
**Pull request by Sopamo**
Fixes #11 :)

### CODE REVIEW

**Comment by fwartner** [comment]
Whoops! Would you please fix?

**Comment by zoltanpeto** [comment]
Hey guys, wouldn't it be better to keep a single pin on the map with a counter indicating how many users are there? Then when you click the pin you could see a list of users. It would definitely perform better once thousands of users are registered (which will happen very soon imo).

**Comment by svenluijten** [comment]
I agree with @zoltanpeto. That would be the best course of action both for usability's sake and performance. I can imagine performance would take a big hit once more than a few 100 users have added a location to their profile, especially on lower end PCs.

**Comment by Sopamo** [comment]
Yeah, that's definitely something we should do as well. I know that there is a plugin for gmaps which does exactly this. We need the randomization anyway because that doesn't help with that as soon as you zoom in.

**Comment by Sopamo** [comment]
@fwartner Ready to merge now :)

**Comment by fwartner** [comment]
bildschirmfoto 2016-08-31 um 00 08 06

Seems your PR was not really clean.. ^^

**Comment by Sopamo** [comment]
Yeah, I already noticed it, didn't occur with my test data :/
I'm on it

**Comment by fwartner** [comment]
May it depends on the amount of users.. (?!)

**Comment by fwartner** [comment]
Please ASAP! :D

**Comment by Sopamo** [comment]
Yeah, just roll back please for the moment :)
Could you provide a dump of the user table? That way I can test with the data that's showing the problem.

**Comment by fwartner** [comment]
Will give it to you on slack.

**Pull request merged**
