### PR TITLE
Create a random, unpredictable temporary password when using social login.

### LINKED ISSUE #3: Temporary password for social login is predictable
Hi! Thank you for the great project.

I found that the temporary password set upon the social login is predictable (you just need to know the username, which is public information).

See the code here: https://github.com/PHPMap/PHPMap/blob/cfff45771d06c947b4db21cfdb5420f3dd3bee2f/app/Http/Controllers/Auth/SocialController.php#L66

The generated password should be random. Using Laravel helper `str_random` (which is based on `random_bytes`) should be enough to get a cryptographically secure random string.

### PR DESCRIPTION
**Pull request by svenluijten**
Fixes #3.

### CODE REVIEW

**Comment by fwartner** [comment]
Thanks. But there the mail-stuff missing. :( Would you add this to your pr?

**Comment by svenluijten** [comment]
can you elaborate on what you mean with "the mail-stuff" @fwartner?

**Comment by svenluijten** [comment]
nevermind, scavenged through the source and found [it](https://github.com/PHPMap/PHPMap/blob/master/resources/views/emails/users/social_welcome_email.blade.php#L3). I'll get working on that when I get home. I assume it can wait a while, right? :wink:

**Comment by fwartner** [comment]
When a user signed up, he gets an email.. (Using the notification-feature in 5.3). The password is atm hardcoded.

Yup. Can wait. :)

It´s in the https://github.com/PHPMap/PHPMap/blob/master/app/Notifications/Users/SignedUpSocial.php#L50

**Comment by svenluijten** [comment]
Oh cool, that makes it even easier than what I had in mind. :smile:

**Comment by fwartner** [comment]
Was just about to ask what happened :D

**Comment by svenluijten** [comment]
My git-fu is leaving me :sweat:

**Comment by fwartner** [comment]
Duh! :(

**Comment by svenluijten** [comment]
I've made a complete mess. Starting over in a new fork :smiley:

**Pull request closed without merging**
