### PR TITLE
Remember map's current properties (lat, lng and zoom) after page reload

### PR DESCRIPTION
**Pull request by nemanjakrstic**
I've decided not to include built files for easier merge.

Should I create a PR with built files?

### CODE REVIEW

**Comment by nemanjakrstic** [comment]
Will do :-)

**Comment by Sopamo** [comment]
Pretty cool feature! Seems like we both stumbled upon the missing dropzone :)
@nemanjakrstic Did you notice as well that the map gets initialized twice? If I remember correctly the this.mapInit(); [here](https://github.com/nemanjakrstic/PHPMap/blob/a19373ea54252887328335355085e5d963baf837/resources/assets/js/components/HomeMap.vue#L15) isn't needed because [this](https://github.com/nemanjakrstic/PHPMap/blob/a19373ea54252887328335355085e5d963baf837/resources/assets/js/components/HomeMap.vue#L16) fires always?

**Comment by nemanjakrstic** [comment]
@Sopamo yes, I've noticed that, but I wasn't sure if that was intentional. I'll do some testing and remove it later if not necessary.

**Comment by Sopamo** [comment]
Great :)

**Pull request merged**
