### PR TITLE
Open user websites/profiles in new tab

### PR DESCRIPTION
**Pull request by gizburdt**
So PHPMap stays open in its own tab.

### CODE REVIEW

**Comment by fwartner** [comment]
Please do ```gulp --production```to compile the assets.

**Comment by gizburdt** [comment]
I didn't change assets, still needed? :)

**Comment by svenluijten** [comment]
You changed `resources/assets/js/components/SingleUser.vue`, that's an asset that needs compiling. @gizburdt

**Comment by gizburdt** [comment]
Oh yeah, stupid me! Sorry! Will run gulp :)

**Comment by gizburdt** [comment]
Done :)

**Comment by svenluijten** [comment]
Thanks!

**Pull request merged**
